Numpy

In [1]:
import numpy as np

In [ ]:
s=np.array(5)
print(s)
v=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

#this means from row : to row
print(v[1:3])
#this means the row,item index
print(v[1,2])

5
6


In [44]:
v_2=np.array([1,2,3,4,5,6])
print(v_2.shape)
print('-'*12)
print(v_2.shape[0])
print('-'*12)
                   #row        column
print(v_2.reshape((v_2.shape[0],1)))
print('-'*12)
#automatically adjusted the column dimension when i wrote -1
print(v_2.reshape((3,-1)))

print('-'*12)
print(v_2[:,None])


(6,)
------------
6
------------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
------------
[[1 2]
 [3 4]
 [5 6]]
------------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


Identity function

In [ ]:
#make a square matrix and give it datatype
mat=np.identity(4,dtype=int)
print(mat)
mat.dtype

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


dtype('int64')

Make a matrix have on item

In [53]:
full_mat=np.full((5,5),6)
full_mat

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

arange()

In [61]:
              #start stop step
range_mat=np.arange(0,50,2)
print(range_mat)
print(range_mat.reshape((5,-1)))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


Random

In [70]:
print(np.random.random((3,3)))
print('-'*12)
print(np.random.randint(1,50,3))
print('-'*12)
print(np.random.choice(range_mat))

[[0.52286069 0.08306303 0.06970442]
 [0.32454154 0.17898528 0.71110227]
 [0.78271851 0.89115786 0.56833241]]
------------
[19 10 34]
------------
40
